<#list domainClasses as domainClass>
<&output file="${domainClass.name}.m">
//
// File generated by Flame.
//

#import "${domainClass.name}.h"


@implementation ${domainClass.name}


@end
</&output>
</#list>