<#list domainClasses as domainClass>
<&output file="${domainClass.name}.h">
//
// File generated by Flame.
//

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


@interface ${domainClass.name} : NSManagedObject

@end
</&output>
</#list>