<#list domainClasses as domainClass>
<&output file="generated/domain/${domainClass.name}.swift">
//
// File generated by Flame.
//

import Foundation

class ${domainClass.name} : NSObject {

    <#list domainClass.properties as property>
    var ${property.name} : ${property.type}

    </#list>

}
</&output>
</#list>