<#list domainClasses as domainClass>
<&output file="generated/domain/${domainClass.name}.swift">
//
// File generated by Flame.
//

import Foundation

class ${domainClass.name} : NSObject {

    <#list domainClass.properties as property>
    var ${property.name} : ${property.type.name}

    </#list>

}
</&output>
</#list>

<#list nativeActions as action>
<&output file="actions/${action.name}.swift">
//
// File generated by Flame.
//

class ${action.name}Action : NSObject {

    class func perform(<#list action.inputs as input>${input.name} : ${input.type.name}<#if input_has_next>, </#if></#list>) {
        // add your implementation here
    }

}
</&output>
</#list>