<#-- TODO remove necessity to add &output tag here -->
<&output file="flame.h">
//
// File generated by Flame.
//

<#list domainClasses as domainClass>
#include "flame/domain/${domainClass.name}.h"
</#list>

<#list composedActions as action>
#include "flame/actions/composed/${action.name}Action.h"
</#list>

<#list nativeActions as action>
#include "flame/actions/native/${action.name}Action.h"
</#list>

</&output>