<#-- TODO remove necessity to add &output tag here -->
<&output file="generated.h">
//
// File generated by Flame.
//

<#list domainClasses as domainClass>
#include "generated/domain/${domainClass.name}.h"
</#list>

<#list composedActions as action>
#include "generated/composed/${action.name}Action.h"
</#list>

<#list nativeActions as action>
#include "generated/headers/${action.name}Action.h"
</#list>

</&output>